apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: security.passrule
spec:
  tier: security
  order: 300
  selector: quarantine != "true"
  namespaceSelector: ''
  serviceAccountSelector: ''
  egress:
    - action: Pass
      source: {}
      destination: {}
  doNotTrack: false
  applyOnForward: false
  preDNAT: false
  types:
    - Egress
